/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBillsRouteImport } from './routes/_app.bills'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppSlotsRouteImport } from './routes/_app.slots'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/bills': typeof AppBillsRoute
  '/customers': typeof AppCustomersRoute
  '/payments': typeof AppPaymentsRoute
  '/sessions': typeof AppSessionsRoute
  '/slots': typeof AppSlotsRoute
  '/vehicles': typeof AppVehiclesRoute
}
export interface FileRoutesByTo {
  '/bills': typeof AppBillsRoute
  '/customers': typeof AppCustomersRoute
  '/payments': typeof AppPaymentsRoute
  '/sessions': typeof AppSessionsRoute
  '/slots': typeof AppSlotsRoute
  '/vehicles': typeof AppVehiclesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/bills': typeof AppBillsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/vehicles': typeof AppVehiclesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/customers'
    | '/payments'
    | '/sessions'
    | '/slots'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bills'
    | '/customers'
    | '/payments'
    | '/sessions'
    | '/slots'
    | '/vehicles'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/bills'
    | '/_app/customers'
    | '/_app/payments'
    | '/_app/sessions'
    | '/_app/slots'
    | '/_app/vehicles'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
